name: flutter_pre_sqa
description: A developer-first Flutter pre-SQA automation tool for validating Flutter projects before QA handoff.
version: 0.1.0
homepage: https://github.com/umardev97/flutter_pre_sqa
repository: https://github.com/umardev97/flutter_pre_sqa
issue_tracker: https://github.com/umardev97/flutter_pre_sqa/issues
documentation: https://github.com/umardev97/flutter_pre_sqa#readme
topics:
  - flutter
  - dart
  - cli
  - static-analysis
  - code-quality
  - sqa
  - quality-assurance
  - testing

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  flutter_pre_sqa: flutter_pre_sqa

dependencies:
  args: ^2.5.0
  path: ^1.9.0
  yaml: ^3.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.26.3
